FROM ubuntu:default 

ENV CONIP=default_ip
RUN apt-get install -y open5gs-pcf &&\
    sed -i "s/127.0.0/$CONIP/g" /etc/open5gs/pcf.yaml &&\
    sed -i "s/localhost/$CONIP.1:27017/g" /etc/open5gs/pcf.yaml &&\
    systemctl restart open5gs-pcrf
