FROM ubuntu:default 

ENV CONIP=default_ip
RUN apt-get install -y open5gs-upf &&\
    sed -i "s/127.0.0/$CONIP/g" /etc/open5gs/upf.yaml &&\
    sed '1,2d' /etc/resolv.conf &&\
    echo 'nameserver 8.8.8.8' > /etc/resolv.conf

RUN echo iptables-persistent iptables-persistent/autosave_v4 boolean false | debconf-set-selections &&\
    echo iptables-persistent iptables-persistent/autosave_v6 boolean false | debconf-set-selections &&\
    apt-get install -y iptables-persistent

ADD rules.v4 /etc/iptables/rules.v4
ADD rules.v6 /etc/iptables/rules.v6
ADD tunup-set.sh tunup-set.sh

ENTRYPOINT ["./tunup-set.sh"]
