FROM ubuntu:default 

ENV CONIP=default_ip
RUN apt-get install -y open5gs-upf &&\
    sed -i "s/127.0.0/$CONIP/g" /etc/open5gs/upf.yaml &&\
    sed '1,2d' /etc/resolv.conf &&\
    echo 'nameserver 8.8.8.8' > /etc/resolv.conf

ADD iptable-set.sh iptable-set.sh

#RUN ./iptables.sh &&\
#    iptables-persistent iptables-persistent/autosave_v4 boolean false | debconf-set-selections &&\
#    iptables-persistent iptables-persistent/autosave_v4 boolean false | debconf-set-selections &&\
#    apt-get -y install iptables-persistent


ENTRYPOINT ["./iptable-set.sh"]
