version: "3"

networks:
  default_network_name:
    driver: bridge
    ipam:
      config:
        - subnet: default_ip.0/24
          gateway: default_ip.252

services:
  mongo:
    container_name: 1_mongo
    image: 1_mongo:latest
    restart: unless-stopped
    ports:
      - 27017:27017
      - 3000:3000
    networks:
      default_network_name:
        ipv4_address: default_ip.1
    volumes:
      - ./data:/data/db
    stdin_open: true
    tty: true
    privileged: true
    entrypoint: /sbin/init
  
  mme:
    container_name: 2_mme
    build:
      context:./coreimages/2_mme
      dockerfile: containerfile
    restart: unless-stopped
    networks:
      default_network_name:
        ipv4_address: default_ip.2
    stdin_open: true
    tty: true
    privileged: true
    entrypoint: /sbin/init
  
  
