version: "3"
services:
  mongo:
    container_name: 1_mongo
    image: 1_mongo:latest
    restart: unless-stopped
    ports:
      - 27017:27017
      - 3000:3000
    networks:
      core:
        ipv4_address: 172.61.0.1
    volumes:
      - ./data:/data/db
    stdin_open: true
    tty: true
    privileged: true
    entrypoint: /sbin/init

networks:
  core:
    driver: bridge
    ipam:
      config:
        - subnet: 172.61.0.0/24
          gateway: 172.61.0.252
