FROM ubuntu:default 

ENV CONIP=default_ip
RUN apt-get install -y open5gs-nrf &&\
    sed -i "s/127.0.0/$CONIP/g" /etc/open5gs/nrf.yaml &&\
    sed -i "s/999/001/g" /etc/open5gs/nrf.yaml &&\
    sed -i "s/70/01/g" /etc/open5gs/nrf.yaml


