# Save the output of this file and use kubectl create -f to import
# it into Kubernetes.
#
# Created with podman-4.6.2
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2024-02-08T04:01:44Z"
  labels:
    app: 5upf-pod
  name: 5upf-pod
spec:
  containers:
  - command:
    - /sbin/init
    image: localhost/nf_separated_container_upf:latest
    name: 5upf
    securityContext:
      privileged: true
    stdin: true
    tty: true
  hostNetwork: true
  hostname: ProLiant-DL380-Gen9

