# Save the output of this file and use kubectl create -f to import
# it into Kubernetes.
#
# Created with podman-4.6.2
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2024-03-08T01:36:08Z"
  labels:
    app: upf-pod
  name: upf-pod
spec:
  containers:
  - command:
    - /sbin/init
    image: localhost/nf_separated_container_upf:latest
    name: upf
    securityContext:
      privileged: true
    stdin: true
    tty: true

