FROM ubuntu:default 

ENV CONIP=default_ip
RUN apt-get install -y open5gs-pcrf &&\
    sed -i "s/127.0.0/$CONIP/g" /etc/freeDiameter/pcrf.conf &&\
    sed -i "s/localhost/$CONIP.1:27017/g" /etc/open5gs/pcrf.yaml &&\
    systemctl restart open5gs-pcrfd
