FROM ubuntu:default 

ENV CONIP=default_ip
RUN apt-get install -y open5gs-hss &&\
    sed -i "s/127.0.0/$CONIP/g" /etc/freeDiameter/hss.conf &&\
    sed -i "s/localhost/$CONIP.1:27017/g" /etc/open5gs/hss.yaml
